config/routes.rb
require "resque_web"
ResqueWeb::Engine.eager_load!

Rails.application.routes.draw do

  # API Routes
  # The constraint is necessary to ensure that :site_name can contain dots
  constraints site_name: %r{[a-z0-9_.-]+} do
    get  'v2/authenticate',                          to: 'api/version2#authenticate'
    get  'v2/proxy_for/:site_name',                  to: 'api/version2#get_proxy'
    post 'v2/report/:site_name/:proxy_id/succeeded', to: 'api/version2#report_result', succeeded: true
    post 'v2/report/:site_name/:proxy_id/failed',    to: 'api/version2#report_result', succeeded: false
  end

  # Admin UI Routes
  resource :activity, only: %i(show), controller: :activity
  resources :sites, only: %i(index show update)
  resources :sources, except: %i(destroy) do
    post 'clear_errors', on: :member
    resource :proxy_list, only: %i(show), controller: :static_list do
      post 'cleanup'
      post 'refresh'
      post 'append'
    end
  end
  resources :proxies, only: %i(show)
  resources :api_keys

  mount ResqueWeb::Engine => "/resque_web"

  get 'config',      to: 'config#show', as: :config
  post 'config/set', to: 'config#set', as: :config_set


  # auth routes
  get '/auth/failure' do
    flash[:notice] = params[:message]
    redirect '/'
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'


  # Map / to the sites page
  root to: 'home#index'
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :proxies, dependent: :destroy, inverse_of: :source

  before_validation :save_config

  # Redis-backed properties
  include Redis::Objects
  list :persistent_errors

  # Ensure all of the necessary configuration options are set
  validate do |source|
    conf = source.config
    source.class.required_fields.each_key do |field_name|
      unless conf.has_key? field_name.to_s and conf[field_name.to_s].present?
        source.errors[:config] << "must contain a '#{field_name}' property."
      end
    end
  end

  def config
    @config ||= JSON.parse(read_attribute(:config))
  end
  
  def config=(new_value)
    @config = new_value
  end

  def save_config
    write_attribute(:config, @config.to_json) if @config
  end
  
  SourceConflict = Struct.new(:conflict_exists?)

  # Pure virtual function intended for child classes to free the proxy resources
  # Parameters:
  #   proxy - The proxy object that is to be decommissioned
  def decommission_proxy(proxy)
    raise NotImplementedError, "Implement #{__callee__} in #{self.class.to_s}"
  end

  # Pure virtual function intended for child classes to create
  # the proxy resources
  # Parameters:
  #   num_proxies - How many proxies to create
  #   site - what site to add the proxies to after they're created
  def provision_proxies(desired_proxy_count, site)
    raise NotImplementedError, "Implement #{__callee__} in #{self.class.to_s}"
  end

  # Enqueues a ProvisionProxies job to create up to num_proxies new proxies.
  # Returns the number of new proxies that should be created after the provision
  def enqueue_provision(site:, num_proxies:)
    return 0 if num_proxies <= 0 || self.proxies.active.count >= self.max_proxies
    desired_proxy_count = self.desired_proxy_count(num_proxies)
    Resque.enqueue_to(self.class.queue, Jobs::ProvisionProxies,
      site.id, self.id, desired_proxy_count
    )
    desired_proxy_count - self.proxies.active.count
  end

  # Pure virtual function intended for child classes to
  # test the saved config by connecting to the remote source.
  # Not part of standard validation because of external dependency
  def validate_config!
    raise NotImplementedError, "Implement #{__callee__} in #{self.class.to_s}"
  end

  # return the number of proxies that would exist if up to num_requested
  # proxies were provisioned
  def desired_proxy_count(num_requested)
    [self.max_proxies, self.proxies.active.count + num_requested].min
  end

  # The given proxy will be decommissioned by a future resque queue.
  # Entry point for child classes to note that a proxy's server is about
  # to be decommissioned.
  def pending_decommission(proxy)
  end

  protected

  # Helper method for child classes to use to add a new proxy to the database
  # when the host and port have been created
  def add_proxy(host, port, username = nil, password = nil, site = Site::NoSite)
    proxy = Proxy.restore_or_initialize host: host, port: port

    return if fix_source_conflicts(proxy).conflict_exists?
    proxy.source = self
    proxy.username = username
    proxy.password = password
    proxy.save
    site.add_proxies(proxy)
  end

  # If a systemic error occurs while provisioning proxies then it gets
  # reported here
  def add_error(error_string)
    time_str = Time.now.to_s
    persistent_errors << "#{time_str}: #{error_string}"
  end

  private

  # Checks the database to see if the given proxy already exists
  # and has a source.  If it does then conflicts are resolved based on the
  # source's reliability
  #
  # Returns:
  # SourceConflict object.  This object has one method, :conflict_exists?
  # This method evaluates to true if the proxy already exists in the database
  # with a source that has a reliability greater than or equal to self.
  def fix_source_conflicts(proxy)
    conflict = SourceConflict.new false
    if !proxy.source.nil? \
      && proxy.source != self

      if proxy.source.reliability < self.reliability
        proxy.source.decommission_proxy(proxy)
      else
        self.decommission_proxy(proxy)
        conflict[:conflict_exists?] = true
      end
    end
    conflict
  end

  class << self
    # queue()
    # Each source gets its own queue for provisioning and decommissioning
    # proxies.  Get the name of that queue as a string
    def queue
      # Keeps only the portion after the last slash
      self.name.underscore.split(%r[/]).last
    end

    def required_fields
      raise NotImplementedError, "Implement #{__callee__} in #{self.to_s}"
    end
    
    def display_name
      # The default implementation of ##display_name takes the name of the class
      # minus any module names, and attempts to convert it into mutliple words
      #   ex.: Sources::DigitalOcean.display_name == "Digital Ocean"
      self.name.underscore.split(%r[/]).last.split(%r[_]).collect(&:capitalize).join ' '
    end
  end
end

app/models/sources/digital_ocean.rb
module Sources
  class DigitalOcean < Sources::Fog
    class << self
      def required_fields
        super.merge({
          client_id: :string,
          api_key: :password,
          image_name: :string,
          flavor_name: :string,
          region_name: :string
        })
      end
    end

    ID_TYPES = ['image', 'flavor', 'region']

    # Connect to Digital Ocean to make sure our config is valid
    def validate_config!
      valid = false
      begin
        names_to_ids # Force re-evaluation of ids
        valid = (!image_id.nil? && !flavor_id.nil? && !region_id.nil?)
      rescue Excon::Errors::Unauthorized => e
        add_error "Invalid credentials"
      end
      valid
    end

    private

    # server_is_proxy_type?(server)
    # given a server, determine if it is running a proxy
    def server_is_proxy_type?(server)
      return server.image_id == self.image_id \
        && server.region_id == self.region_id \
        && server.flavor_id == self.flavor_id
    end

    def connection
      @connection ||= ::Fog::Compute.new(
        :provider => 'DigitalOcean',
        :digitalocean_api_key => config['api_key'],
        :digitalocean_client_id => config['client_id']
      )
    end

    def server_by_proxy(proxy)
      return NoServer unless validate_config!
      server = connection.servers.select do |s|
        s.public_ip_address == proxy.host
      end.first

      server || NoServer
    end

    # The ID_TYPES methods all are very similar, so dynamically create all
    # of them at once
    ID_TYPES.each do |id_type|
      class_eval <<-RUBY
        # image_id()
        # flavor_id()
        # region_id()
        # Get the image/flavor/region id.
        # If the id is undefined, translate image/flavor/region name to id by
        # connecting to Digital Ocean.
        # Returns cached value if already calculated
        # Parameters:
        #   None
        # Returns:
        #   - a numeric id representing the image/flavor/region on Digital Ocean
        #   - nil if not found
        def #{id_type}_id
          key = '#{id_type}_id'
          return config[key] if config.has_key?(key)
          names_to_ids
          config[key]
        end

        # retrieve_image_id()
        # retrieve_flavor_id()
        # retrieve_region_id()
        # Retrieve image/flavor/region id from Digital Ocean
        # If the id is not found then adds to the source's persistent error log
        # Parameters:
        #   None
        # Returns:
        #   - a numeric id representing the image/flavor/region on Digital Ocean
        #   - nil if not found
        def retrieve_#{id_type}_id
          name = config['#{id_type}_name']
          id = connection.#{id_type.pluralize}.select do |i|
            i.name == name
          end.first.andand.id
          if id.nil?
            names = connection.#{id_type.pluralize}.map(&:name).join(", ")
            add_error "There is no #{id_type} named \#{name}. " \
              "Options are: \#{names}"
          end
          id
        end
      RUBY
    end

    # names_to_ids()
    # Retrieve all ids from the server and save them in the database
    # Does not save to the database if at least one id is nil.
    # Parameters:
    #   None
    def names_to_ids
      config['image_id'] = retrieve_image_id
      config['flavor_id'] = retrieve_flavor_id
      config['region_id'] = retrieve_region_id
      unless config['image_id'].nil? \
        || config['flavor_id'].nil? \
        || config['region_id'].nil?

        self.save
      end
    end

    def create_server
      timestamp = Time.now.strftime("%Y.%m.%d-%H.%M.%S")
      connection.servers.create(
        name: "proxy-#{timestamp}-#{SecureRandom.uuid}",
        image_id: image_id,
        flavor_id: flavor_id,
        region_id: region_id
      )
    # Generally get this error when we've hit our limit on # of servers
    rescue Excon::Errors::Forbidden => e
      add_error(JSON.parse(e.response.body)['error_message'])
      NoServer
    end
  end
end

app/models/sources/joyent.rb
module Sources
  class Joyent < Sources::Fog
    class << self
      def required_fields
        super.merge({
          username: :string,
          password: :password,
          datacenter: :string,
          image_id: :string,
          package_id: :string
        })
      end
    end

    # Connect to Joyent to make sure our config is valid
    # You cannot verify custom images through Fog, but an incorrect image
    # UUID will cause an error when creating the server.
    def validate_config!
      if !config['image_id'].nil?
        connection.flavors.each do |f|
          if f.name == config['package_id']
            return true
          end
        end
      end
      return false
    end

    private

    # server_is_proxy_type?(server)
    # given a server, determine if it is running a proxy
    def server_is_proxy_type?(server)
      return server.image == config['image_id'] \
        && server.package == config['package_id']
    end

    def connection
      @connection ||= ::Fog::Compute.new(
        :provider => 'Joyent',
        :joyent_username => config['username'],
        :joyent_password => config['password'],
        :joyent_url => config['datacenter']
      )
    end

    def server_by_proxy(proxy)
      return NoServer unless validate_config!
      server = connection.servers.select do |s|
        s.primary_ip == proxy.host
      end.first

      server || NoServer
    end

    def create_server
      timestamp = Time.now.strftime("%Y.%m.%d-%H.%M.%S")
      server_output = connection.servers.create(
        name: "proxy-#{timestamp}-#{SecureRandom.uuid}",
        package: config['package_id'],
        image: config['image_id']
      )
    # Generally get this error when we've hit our limit on # of servers
    # but Joyent will produce errors here as well if form data is incorrect
    rescue => e
      puts(e)
      add_error(e.message)
      NoServer
    end
  end
end

app/models/sources/static.rb
module Sources
  class Static < Source
    def decommission_proxy(proxy)
      # Do nothing. The Proxy instance is already going to be deleted.
    end

    def provision_proxies(desired_proxy_count, site)
      # Do nothing. There's no automatic way to provision proxies from a static list.
    end

    def validate_config!
      true  # No config to validate
    end

    def max_proxies
      0  # Never try to provision extra proxies from a static list
    end

    # Expose the add_proxy method publicly
    def add_proxy(host, port, username = nil, password = nil, site = Site::NoSite)
      super
    end

    class << self
      def required_fields; {}; end
      def display_name; "Static List"; end
    end
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_filter :assign_source, only: %i(edit update show clear_errors)
  
  def index
  end
  
  def new
    @source = Source.new
    @source.config = {}
    @source_types = Zartan::SourceType.all
  end
  
  def create
    source_class = Source
    begin
      source_class = params[:source_type].constantize
    rescue
      flash.now[:error] = "Please select a source type"
    end
    
    @source = source_class.new(base_parameters)
    @source.config = config_parameters
    
    if source_class != Source and @source.valid?
      @source.save!
      redirect_to source_path(@source)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    @source.assign_attributes(base_parameters)
    old_source_config = @source.config
    new_source_config = config_parameters
    
    # Retain the old value of each password-type config field if the user didn't
    # supply one.
    @source.class.required_fields.select { |name, type| type == :password }.each do |name, _|
      name = name.to_s
      new_source_config[name] = old_source_config[name] if new_source_config[name].empty?
    end
    @source.config = new_source_config
    
    if @source.valid?
      @source.save!
      redirect_to source_path(@source)
    else
      render :edit
    end
  end
  
  def show
  end
  
  def clear_errors
    @source.persistent_errors.clear
    redirect_to source_path(@source)
  end
  
  private
  def assign_source
    @source = Source.find(params[:id])
  end
  
  def base_parameters
    params.require(:source).permit(:name, :max_proxies, :reliability)
  end
  
  def config_parameters
    params.require(:config).to_unsafe_h rescue {}
  end
end

app/helpers/source_helper.rb
module SourceHelper
end

app/views/sources/_source_config.html.erb
<% source_type.required_fields.each_pair do |name, type| %>
  <% name = name.to_s %>
  <div class="form-group">
    <label for="source<%= source_type.name.gsub(/::/,'') + name.capitalize %>" class="control-label col-sm-3"><%= name %></label>
    <div class="col-sm-9">
      <% if type == :password %>
        <input type="password" name="config[<%= name %>]" class="form-control" id="source<%= source_type.name.gsub(/::/,'') + name.capitalize %>">
        <% if show_help %><span class="help-block">Leave this blank to keep the same <%= name %>, or fill in a new <%= name %> to reset it.</span><% end %>
      <% else %>
        <input type="text" name="config[<%= name %>]" class="form-control" id="source<%= source_type.name.gsub(/::/,'') + name.capitalize %>" value="<%= values.fetch(name,'') %>" placeholder="<%= name %>">
      <% end %>
    </div>
  </div>
<% end %>

app/views/sources/edit.html.erb
<div class="page-header">
  <h1>Edit Source <%= @source.name %></h1>
</div>
<% if @source.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@source.errors.count, "error") %> were encountered while updating this source.</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @source.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for @source, url: {action: "update"}, html: {class: "form-horizontal col-lg-8 col-lg-offset-2"} do |f| %>
  <div class="form-group">
    <label for="sourceName" class="control-label col-sm-3">Name</label>
    <div class="col-sm-9">
      <input type="text" name="source[name]" class="form-control" id="sourceName" placeholder="Name" value="<%= @source.name %>">
    </div>
  </div>
  <div class="form-group">
    <label for="sourceType" class="control-label col-sm-3">Type</label>
    <div class="col-sm-9">
      <select id="sourceType" class="form-control" disabled>
        <option selected disabled><%= @source.class.display_name %></option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="sourceMaxProxies" class="control-label col-sm-3">Max Proxies</label>
    <div class="col-sm-9">
      <input type="text" name="source[max_proxies]" class="form-control" id="sourceMaxProxies" placeholder="Max Proxies" value="<%= @source.max_proxies %>">
    </div>
  </div>
  <div class="form-group">
    <label for="sourceReliability" class="control-label col-sm-3">Reliability Score</label>
    <div class="col-sm-9">
      <input type="text" name="source[reliability]" class="form-control" id="sourceName" value="<%= @source.reliability %>">
    </div>
  </div>
  <%= render partial: 'source_config', locals: { source_type: @source.class, values: @source.config, show_help: true } %>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <button type="submit" class="btn btn-primary">Save</button>
      <%= link_to "Cancel", source_path(@source), class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sources/index.html.erb
<div class="page-header">
  <%= link_to "New Source",
              new_source_path,
              :class => 'btn btn-primary pull-right' %>
  <h1>Proxy Sources</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Proxies (current/max)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% Source.all.each do |source| %>
      <tr>
        <td>
          <%= link_to source.name, source_path(source) %>
          <% unless source.persistent_errors.empty? %>
            <span class="label label-danger"><%= pluralize(source.persistent_errors.count,"error") %></span>
          <% end %>
        </td>
        <td><%= source.class.display_name %></td>
        <td><%= source.proxies.active.count %> / <%= source.max_proxies %></td>
        <td>
          <%= link_to "Edit", edit_source_path(source), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sources/new.html.erb
<div class="page-header">
  <h1>New Source</h1>
</div>
<% if @source.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@source.errors.count, "error") %> were encountered while creating this source.</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @source.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for @source, url: {action: "create"}, html: {class: "form-horizontal col-lg-8 col-lg-offset-2"} do |f| %>
  <div class="form-group">
    <label for="sourceName" class="control-label col-sm-3">Name</label>
    <div class="col-sm-9">
      <input type="text" name="source[name]" class="form-control" id="sourceName" placeholder="Name" value="<%= @source.name %>">
    </div>
  </div>
  <div class="form-group">
    <label for="typeSelector" class="control-label col-sm-3">Type</label>
    <div class="col-sm-9">
      <select id="typeSelector" class="form-control">
        <option disabled selected>Select Type</option>
        <% @source_types.each do |source_type| %>
          <option value="<%= source_type.name.gsub(/::/,'') %>"><%= source_type.display_name %></option>
        <% end %>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="sourceMaxProxies" class="control-label col-sm-3">Max Proxies</label>
    <div class="col-sm-9">
      <input type="text" name="source[max_proxies]" class="form-control" id="sourceMaxProxies" placeholder="Max Proxies" value="<%= @source.max_proxies %>">
    </div>
  </div>
  <div class="form-group">
    <label for="sourceReliability" class="control-label col-sm-3">Reliability Score</label>
    <div class="col-sm-9">
      <input type="text" name="source[reliability]" class="form-control" id="sourceName" value="<%= @source.reliability %>">
    </div>
  </div>
  <div id="configTarget"></div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <button type="submit" class="btn btn-primary">Create</button>
      <%= link_to "Cancel", sources_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

<div id="configForms">
  <% @source_types.each do |source_type| %>
    <div id="sourceType<%= source_type.name.gsub(/::/,'') %>" class="configBlock">
      <input type="hidden" name="source_type" value="<%= source_type.name %>">
      <%= render partial: 'source_config', locals: { source_type: source_type, values: @source.config, show_help: false } %>
    </div>
  <% end %>
</div>

app/views/sources/show.html.erb
<div class="page-header">
  <span class="pull-right">
    <%= link_to "Back", sources_path, :class => 'btn btn-default'  %>
    <%= link_to "Edit", edit_source_path(@source), :class => 'btn btn-default' %>
    <% if @source.is_a? Sources::Static %>
      <%= link_to "Manage Unhealthy Proxies", source_proxy_list_path(@source), :class => 'btn btn-default' %>
    <% end %>
  </span>
  <h1>Source <%= @source.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Source Type:</strong></dt>
  <dd><%= @source.class.display_name %></dd>
  <dt><strong>Reliability Score:</strong></dt>
  <dd><%= @source.reliability %></dd>
  <% @source.class.required_fields.each_pair do |field, type| %>
    <% unless type == :password %>
      <dt><strong><%= field %>:</strong></dt>
      <dd><%= @source.config[field.to_s] %></dd>
    <% end %>
  <% end %>
</dl>

<% unless @source.persistent_errors.empty? %>
  <h2>
    <%= form_for @source, url: {action: 'clear_errors'}, method: 'POST', html: {class: 'form-inline pull-right'} do |f| %>
      <button type="submit" class="btn btn-default">Clear Errors</button>
    <% end %>
    Errors
  </h2>

  <ul class="list-group">
    <% @source.persistent_errors.each do |err| %>
      <li class="list-group-item list-group-item-danger"><%= err %></li>
    <% end %>
  </ul>
<% end %>

<h2>
  Proxies
  <small>Current: <%= @source.proxies.active.count %>; Max: <%= @source.max_proxies %></small>
</h2>

<div class="list-group">
  <% @source.proxies.active.each do |proxy| %>
    <%= link_to "#{proxy.host}:#{proxy.port}", proxy_path(proxy), :class => 'list-group-item' %>
  <% end %>
</div>