config/routes.rb
require "resque_web"
ResqueWeb::Engine.eager_load!

Rails.application.routes.draw do

  # API Routes
  # The constraint is necessary to ensure that :site_name can contain dots
  constraints site_name: %r{[a-z0-9_.-]+} do
    get  'v2/authenticate',                          to: 'api/version2#authenticate'
    get  'v2/proxy_for/:site_name',                  to: 'api/version2#get_proxy'
    post 'v2/report/:site_name/:proxy_id/succeeded', to: 'api/version2#report_result', succeeded: true
    post 'v2/report/:site_name/:proxy_id/failed',    to: 'api/version2#report_result', succeeded: false
  end

  # Admin UI Routes
  resource :activity, only: %i(show), controller: :activity
  resources :sites, only: %i(index show update)
  resources :sources, except: %i(destroy) do
    post 'clear_errors', on: :member
    resource :proxy_list, only: %i(show), controller: :static_list do
      post 'cleanup'
      post 'refresh'
      post 'append'
    end
  end
  resources :proxies, only: %i(show)
  resources :api_keys

  mount ResqueWeb::Engine => "/resque_web"

  get 'config',      to: 'config#show', as: :config
  post 'config/set', to: 'config#set', as: :config_set


  # auth routes
  get '/auth/failure' do
    flash[:notice] = params[:message]
    redirect '/'
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'


  # Map / to the sites page
  root to: 'home#index'
end

app/models/proxy.rb
class Proxy < ActiveRecord::Base
  belongs_to :source, inverse_of: :proxies
  has_many :proxy_performances, dependent: :destroy, inverse_of: :proxy
  has_many :sites, through: :proxy_performances

  include Concerns::SoftDeletable

  class << self
    # Retrieve active proxies from the database from a specific source that are
    # currently unaffiliated with a site
    def retrieve(source:, site:, max_proxies:)
      assosciated_proxy_ids = ProxyPerformance.where(site: site).map(&:proxy_id)
      self.active.where(source: source).reject { |p|
        assosciated_proxy_ids.include? p.id
      }.take(max_proxies)
    end

    def restore_or_initialize(host:, port:)
      proxy = self.find_or_initialize_by(host: host, port: port)
      proxy.source = nil
      proxy.deleted_at = nil
      proxy.proxy_performances.each do |pp|
        pp.destroy()
      end
      proxy
    end
  end

  def queue_decommission
    if self.no_sites?
      source.pending_decommission(self)
      Resque.enqueue_to(self.source.class.queue, Jobs::DecommissionProxy, self.id)
    end
  end

  # Check to make sure the proxy is a candidate for being decomissioned.
  # If any sites are still using the proxy then leave it be.
  # If no sites are still using the proxy, soft-delete the proxy and perform
  # source-specific work to tear down the proxy
  def decommission
    actually_decomission = false

    self.transaction(Zartan::Application.config.default_transaction_options) do
      if self.no_sites?
        # soft-delete the proxy so that nobody else tries to use it
        self.soft_delete
        self.save
        # Decomission the proxy outside of the transaction
        actually_decomission = true
      end
    end
    # Tear down the proxy outside of the transaction because we don't need
    # the database anymore.
    self.source.decommission_proxy(self) if actually_decomission
  end

  # Returns true if there are no sites actively connected to the proxy.
  def no_sites?
    self.proxy_performances.active.empty?
  end

  NoProxy = Class.new
  NotReady = Struct.new(:proxy_ts, :threshold_ts, :proxy_id) do
    def timeout
      proxy_ts - threshold_ts
    end
  end
end

app/controllers/proxies_controller.rb
class ProxiesController < ApplicationController
  def show
    @proxy = Proxy.find(params[:id])
  end
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/views/proxies/show.html.erb
<div class="page-header">
  <h1>Proxy <%= @proxy.host %>:<%= @proxy.port %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Source:</strong></dt>
  <dd><%= link_to @proxy.source.name, source_path(@proxy.source) %> (<%= @proxy.source.class.display_name %>)</dd>
</dl>

<h2>
  Site Performance
</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Site</th>
      <th>Total Attempts</th>
      <th>Successes</th>
      <th>Failures</th>
    </tr>
  </thead>
  <tbody>
    <% if @proxy.proxy_performances.active.count > 0 %>
      <% @proxy.proxy_performances.active.each do |perf| %>
        <% s, f = perf.times_succeeded, perf.times_failed %>
        <tr>
          <td><%= link_to perf.site.name, site_path(perf.site) %></td>
          <td><%= s + f %>
          <td><%= s %> <% if s + f > 0 %>(<%= (100 * s.to_f / (s + f)).round(2) %>%)<% end %></td>
          <td><%= f %> <% if s + f > 0 %>(<%= (100 * f.to_f / (s + f)).round(2) %>%)<% end %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">
          <p class="lead text-center">This proxy isn't associated with any sites yet.</p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>