config/routes.rb
require "resque_web"
ResqueWeb::Engine.eager_load!

Rails.application.routes.draw do

  # API Routes
  # The constraint is necessary to ensure that :site_name can contain dots
  constraints site_name: %r{[a-z0-9_.-]+} do
    get  'v2/authenticate',                          to: 'api/version2#authenticate'
    get  'v2/proxy_for/:site_name',                  to: 'api/version2#get_proxy'
    post 'v2/report/:site_name/:proxy_id/succeeded', to: 'api/version2#report_result', succeeded: true
    post 'v2/report/:site_name/:proxy_id/failed',    to: 'api/version2#report_result', succeeded: false
  end

  # Admin UI Routes
  resource :activity, only: %i(show), controller: :activity
  resources :sites, only: %i(index show update)
  resources :sources, except: %i(destroy) do
    post 'clear_errors', on: :member
    resource :proxy_list, only: %i(show), controller: :static_list do
      post 'cleanup'
      post 'refresh'
      post 'append'
    end
  end
  resources :proxies, only: %i(show)
  resources :api_keys

  mount ResqueWeb::Engine => "/resque_web"

  get 'config',      to: 'config#show', as: :config
  post 'config/set', to: 'config#set', as: :config_set


  # auth routes
  get '/auth/failure' do
    flash[:notice] = params[:message]
    redirect '/'
  end
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'


  # Map / to the sites page
  root to: 'home#index'
end

app/controllers/static_list_controller.rb
class StaticListController < ApplicationController
  before_filter :assign_source

  def show
    @unhealthy_proxies = unhealthy_proxies
  end

  def cleanup
    unhealthy_proxies.each do |proxy|
      proxy.destroy
    end
    flash[:info] = "All unhealthy proxies have been cleared."
    redirect_to action: :show
  end

  def refresh
    proxy_list = unhealthy_proxies.to_a
    proxy_list.each do |proxy|
      proxy.proxy_performances.clear
      proxy.deleted_at = nil
      proxy.save
    end
    Site.all.each do |site|
      site.add_proxies(*proxy_list)
    end
    flash[:info] = "All previously unhealthy proxies have been refreshed and added back to the proxy pool."
    redirect_to action: :show
  end

  def append
    new_proxy_list = params[:new_proxy_list]
    errors = []
    proxies_added = []

    # Iterate through the lines of the proxy list
    new_proxy_list.each_line do |proxy_spec|
      proxy_spec.strip!
      next if proxy_spec.empty? or proxy_spec =~ /^#/

      # Extract the username, password, host, and port from each line
      host, port, username, password = nil, nil, nil, nil
      case proxy_spec
      when /^(.+):(.+)@([0-9.]+):([0-9]+)$/
        host = $3
        port = $4.to_i
        username = $1
        password = $2
      when /^([0-9.]+):([0-9]+)$/
        host = $1
        port = $2.to_i
      else
        errors << "Invalid proxy specification: #{proxy_spec}"
        next
      end

      # Create the new proxy if it doesn't already exist
      if @source.proxies.active.where(host: host, port: port).count > 0
        errors << "Proxy #{proxy_spec} already exists."
      else
        @source.add_proxy(host, port, username, password)
        proxies_added << @source.proxies.where(host: host, port: port).first
      end
    end

    # Add all of the new proxies to each site
    Site.all.each do |site|
      site.add_proxies(*proxies_added)
    end

    # Report all errors, if any
    unless errors.empty?
      flash[:error] = errors
    end

    flash[:info] = "#{proxies_added.count} new proxies added."

    redirect_to action: :show
  end

  private
  def assign_source
    @source = Source.find(params[:source_id])
    unless @source and @source.is_a? Sources::Static
      flash[:error] = "Unhealthy proxy management is only available for static sources."
      redirect_to source_path(@source)
    end
  end

  def unhealthy_proxies
    @source.proxies.where('deleted_at IS NOT NULL')
  end
end

app/views/static_list/show.html.erb
<div class="page-header">
  <span class="pull-right">
    <%= link_to "Back", source_path(@source), :class => 'btn btn-default'  %>
  </span>
  <h1>Unhealthy Proxy List for <%= @source.name %></h1>
</div>

<h2>
  <span class="pull-right">
    <%= link_to("Return All to Pool", refresh_source_proxy_list_path(@source), method: :post, class: 'btn btn-default') %>
    <%= link_to("Delete All", cleanup_source_proxy_list_path(@source), method: :post, class: 'btn btn-danger') %>
  </span>
  Unhealthy Proxies
</h2>
<% if @unhealthy_proxies.empty? %>
  <p class="lead text-center">No unhealthy proxies</p>
<% else %>
  <pre><%= @unhealthy_proxies.map { |proxy|
    "#{proxy.username}:#{proxy.password}@#{proxy.host}:#{proxy.port}"
  }.join("\n") %></pre>
<% end %>

<h2>Add New Proxies</h2>
<p>Enter proxies below, one per line, in the form of <code>username:password@ip:port</code>.</p>
<%= form_tag(append_source_proxy_list_path(@source), method: 'POST') do %>
  <div class="form-group">
    <textarea class="form-control" rows="8" name="new_proxy_list"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Add proxies</button>
<% end %>